#!/bin/bash

echo 'INSTRUCTIONS:'
echo 'Put the extracted "firefox" folder in the same folder as this script.'
echo 'Allow this script to be run as application.'
echo 'Run this script in a terminal window.'

echo '~#~'

if [ "$EUID" -ne 0 ]; then
    echo 'Warning: No super-user authorization. Proceeding with unprivileged-user instalation'
    echo "Installing Firefox Developer Edition to $HOME/.local/share/"
  
    INSTALL_LOCATION=$HOME/.local/share
    HOOK_LOCATION=$HOME/.local
  
  else
    echo 'Warning: Super-user authorized. Proceeding with super-user instalation'
    echo 'Installing Firefox Developer Edition to /opt/'
  
    INSTALL_LOCATION=/opt
    HOOK_LOCATION=/usr
fi

echo "Moving files to $INSTALL_LOCATION"
mv $(pwd)/firefox $INSTALL_LOCATION/firefox-dev
ln -s $INSTALL_LOCATION/firefox-dev/firefox $HOOK_LOCATION/bin/firefox-dev

echo "Linking icon to $HOOK_LOCATION"
mkdir -p $HOOK_LOCATION/share/hicolor/128x128/apps
ln -s $INSTALL_LOCATION/firefox-dev/browser/chrome/icons/default/default128.png $HOOK_LOCATION/share/hicolor/128x128/apps/firefox-dev.png

echo "Creating Desktop file in $HOOK_LOCATION"
cp $(pwd)/firefox-dev.desktop $HOOK_LOCATION/share/applications/

echo '~#~'

echo 'Done!'
echo 'Please restart your session if there are any visible errors.'
