#!/bin/bash

echo 'INSTRUCTIONS:'
echo 'Put the extracted "firefox" folder in the same folder as this script.'
echo 'Allow this script to be run as application.'
echo 'Run this script as super-user in a terminal window.'

echo '~#~'

if [ "$EUID" -ne 0 ]; then
  echo 'Error: No super-user authorization.'
  echo 'You can type the command "sudo !!" to re-run this script as super-user.'
  exit 1
fi

echo 'Installing...'

mv ./firefox /opt/firefox-developer
mkdir -p /usr/share/app-info/icons/firefox-developer/128x128

ln -s /opt/firefox-developer/firefox /usr/bin/firefox-developer
ln -s /opt/firefox-developer/browser/chrome/icons/default/default128.png /usr/share/app-info/icons/firefox-developer/128x128/firefox-developer-icon.png

cp ./firefox-developer.desktop /usr/share/applications/

echo '~#~'

echo 'Done!'
echo 'Please restart your session if there are any visible errors.'
