#!/bin/sh

echo 'INSTRUCTIONS:'
echo 'Put the extracted "firefox" and / or "thunderbird" folders in the same folder as this script.'
echo 'Allow this script to be run as application.'
echo 'Run this script in a terminal window.'

echo '~#~'

# Set Install Location Variables
if [ "$EUID" -ne 0 ]; then
    echo 'Warning: No super-user authorization. Proceeding with unprivileged-user installation'
    INSTALL_LOCATION="$HOME/.local/share"
    HOOK_LOCATION="$HOME/.local"
    ENVIRONMENT_LOCATION="$HOME/.config"
  else
    echo 'Warning: Super-user authorized. Proceeding with root installation'
    INSTALL_LOCATION="/opt"
    HOOK_LOCATION="/usr"
    ENVIRONMENT_LOCATION="/etc"
fi

# Prepare for Install
echo "Installing on $INSTALL_LOCATION"
for DIRECTORY in $(ls -d */); do

    APPLICATION=${DIRECTORY%%/};

    if [ $APPLICATION == 'thunderbird' ]; then
        BINARY_NAME='thunderbird'
        ICON_LOCATION='chrome'
    else
        BINARY_NAME='firefox'
        ICON_LOCATION='browser/chrome'
    fi
    
    echo "Moving files to $INSTALL_LOCATION"
    mv "$(pwd)/$APPLICATION" "$INSTALL_LOCATION/"
    mkdir -p "$HOOK_LOCATION/bin"
    ln -s "$INSTALL_LOCATION/$APPLICATION/$BINARY_NAME" "$HOOK_LOCATION/bin/$APPLICATION"

    echo "Linking icon to $HOOK_LOCATION/share/icons/hicolor/128x128/apps/"
    mkdir -p "$HOOK_LOCATION/share/icons/hicolor/128x128/apps"
    ln -s "$INSTALL_LOCATION/$APPLICATION/$ICON_LOCATION/icons/default/default128.png" "$HOOK_LOCATION/share/icons/hicolor/128x128/apps/$APPLICATION.png"

    echo "Creating Desktop file in $HOOK_LOCATION/share/applications/"
    TITLE=$(grep "Title=" "$INSTALL_LOCATION/$APPLICATION/updater.ini" | head -c -8 | tail -c +7)
    wget --https-only "https://src.fedoraproject.org/rpms/$BINARY_NAME/raw/rawhide/f/$BINARY_NAME.desktop"
    sed -i -e "0,/Name=.*/s/Name=.*/Name=$TITLE/" "$(pwd)/$BINARY_NAME.desktop"
    sed -i -e "s/^Icon=.*/Icon=$APPLICATION.png/" "$(pwd)/$BINARY_NAME.desktop"
    sed -i -e "s/^Exec=$BINARY_NAME/Exec=$APPLICATION/" "$(pwd)/$BINARY_NAME.desktop"
    mkdir -p "$HOOK_LOCATION/share/applications"
    mv "$(pwd)/$BINARY_NAME.desktop" "$HOOK_LOCATION/share/applications/$APPLICATION.desktop"

    echo '~#~'

done

# Set Relevant Environment Variables
if [ $XDG_SESSION_TYPE == 'wayland' ]; then
    mkdir -p "$ENVIRONMENT_LOCATION/environment.d"
    echo 'MOZ_ENABLE_WAYLAND=1' >> "$ENVIRONMENT_LOCATION/environment.d/mozilla.conf"
fi

if [ $XDG_CURRENT_DESKTOP == 'KDE' ]; then
    mkdir -p "$ENVIRONMENT_LOCATION/environment.d"
    echo 'GTK_USE_PORTAL=1' >> "$ENVIRONMENT_LOCATION/environment.d/mozilla.conf"
fi

# Clear Custom Variables
unset INSTALL_LOCATION
unset HOOK_LOCATION
unset APPLICATION
unset BINARY_NAME
unset ICON_LOCATION
unset ENVIRONMENT_LOCATION
unset TITLE
unset DIRECTORY

echo 'Done!'
echo 'Please restart your session if there are any visible errors.'
