#!/bin/bash

echo 'INSTRUCTIONS:'
echo 'Allow this script to be run as application.'
echo 'Run this script as the user that installed this application in a terminal window.'

echo '~#~'

if [ "$EUID" -ne 0 ]; then
    echo 'Warning: No super-user authorization. Proceeding with the removal for the unprivileged-user installation'
    echo "Removing Firefox Developer Edition from $HOME/.local/share/"
  
    INSTALL_LOCATION=$HOME/.local/share
    HOOK_LOCATION=$HOME/.local
    
  else
    echo 'Warning: Super-user authorized. Proceeding with the removal for the super-user instalation'
    echo 'Removing Firefox Developer Edition from /opt/'
  
    INSTALL_LOCATION=/opt
    HOOK_LOCATION=/usr
    
fi

echo "Removing files from $INSTALL_LOCATION"
rm -r $INSTALL_LOCATION/firefox-dev
rm $HOOK_LOCATION/bin/firefox-dev

echo "Removing icon from $HOOK_LOCATION/share/icons/hicolor/128x128/apps/"
rm $HOOK_LOCATION/share/icons/hicolor/128x128/apps/firefox-dev.png

echo "Removing Desktop file from $HOOK_LOCATION/share/applications/"
rm $HOOK_LOCATION/share/applications/firefox-dev.desktop

echo '~#~'

echo 'Done!'
echo 'Please restart your session if there are any visible errors.'
